DROP TABLE IF EXISTS PEDIDO;
CREATE TABLE PEDIDO(
      ID INTEGER IDENTITY PRIMARY KEY,
      EMAIL VARCHAR(255) NOT NULL,
      FULLNAME VARCHAR(255) NOT NULL,
      TEL VARCHAR(255) NOT NULL,
      PERSONAS INTEGER NOT NULL,
      FECHA DATE NOT NULL,
      MOMENTO VARCHAR(255) NOT NULL,
      CIUDAD VARCHAR(255) NOT NULL,
      DIR1 VARCHAR(255) NOT NULL,
      PRECIO NUMBER,
      ESTADO VARCHAR(255)
);